# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://blog.techrelay.xyz/"  # Include trailing slash
# title = "Clarity"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Copyright Â© 2020-2022 Tech Relay and Lamda Inc."
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"
disqusShortname = ""

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
