[[main]]
name = "Home"
url = ""
weight = "-111"
[[main]]
name = "Blog Posts"
url = "post/"
weight = "-110"
[[main]]
name = "About"
url = "about/"
weight = "-109"
[[main]]
name = "Contact"
url = "contact/"
weight = "-108"
[[main]]
name = "Contribute"
url = "contribute/"
weight = "-107"
[[main]]
identifier = "Links"
name = "Links"
weight = "-105"
[[main]]
name = "Matrix"
parent = "Links"
url = "https://matrix.techrelay.xyz"
[[main]]
name = "Search"
url = "/search"
weight = "-104"
[[social]]
name = "github"
type = "social"
url = "https://github.com/techrelay"
weight = 1
[[social]]
name = "twitter"
url = "https://twitter.com/techrelay"
weight = 2
[[social]]
name = "rss"
url = "index.xml"
weight = 4
